[package]
name = "rust-view-aln"
version = "0.1.0"
edition = "2021"

[dependencies]
build_html = "2.5.0"
bwrap = "1.3.0"
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
serde = { version = "1.0.215", features = ["derive"] }
textwrap = "0.16.1"
wasm-bindgen = "0.2.95"
